In [306]:
import numpy as np

In [390]:
f=open('data1.txt')
a=[]
y=[]
x=[]
for line in f :
    a.append(line.replace('\n','\t').split('\t')[0:4])
for i in a:
    y.append(i[0])
    x.append(float(i[1]))
    x.append(float(i[2]))
    x.append(float(i[3]))
X=np.array(x)
Y=np.array(y)
X=X.reshape(-1,3) # back to 2D representation
print X[0]

[-1.06302559  4.34787035  8.78193188]


In [391]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit(Y)
lb.classes_
Y=lb.transform(Y) # Y is now a one Hot vector
Y.shape
X=preprocessing.normalize(X)

[-0.10784703  0.44110404  0.89095243]


In [376]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33)

In [377]:
from keras.models import Sequential 
from keras.layers import Dense,Dropout
lam_bda = 0.2
from keras import regularizers

In [378]:
model = Sequential()
model.add(Dense(46, input_dim=3, activation='sigmoid'))
#model.add(Dropout(0.8))
#model.add(Dense(46, activation='sigmoid')) # 46 in data1 41 in data2
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model
model.fit(X_train, y_train, epochs=15, batch_size=10)

Epoch 1/15
542/542 [==============================] - 0s 639us/step - loss: 0.6558 - acc: 0.6403
Epoch 2/15
542/542 [==============================] - 0s 123us/step - loss: 0.5973 - acc: 0.7855
Epoch 3/15
542/542 [==============================] - 0s 132us/step - loss: 0.5451 - acc: 0.9471
Epoch 4/15
542/542 [==============================] - 0s 126us/step - loss: 0.4987 - acc: 0.9778
Epoch 5/15
542/542 [==============================] - 0s 114us/step - loss: 0.4575 - acc: 0.9783
Epoch 6/15
542/542 [==============================] - 0s 139us/step - loss: 0.4209 - acc: 0.9783
Epoch 7/15
542/542 [==============================] - 0s 116us/step - loss: 0.3884 - acc: 0.9783
Epoch 8/15
542/542 [==============================] - 0s 136us/step - loss: 0.3596 - acc: 0.9783
Epoch 9/15
542/542 [==============================] - 0s 141us/step - loss: 0.3341 - acc: 0.9783
Epoch 10/15
542/542 [==============================] - 0s 129us/step - loss: 0.3114 - acc: 0.9783
Epoch 11/15
542/542 [========

In [379]:
y_pred = model.predict(X_test)
count = 0 
for i in range(y_test.shape[0]):
    if np.argmax(y_pred[i]) == np.argmax(y_test[i]):
        count = count + 1
print count

25


In [380]:
Y_new = np.zeros(Y.shape[0])
for j in range(Y.shape[0]):
    Y_new[j] = int(np.argmax(Y[j]))
print Y_new[3]

30.0


In [381]:
X_new_train, X_new_test, y_new_train, y_new_test = train_test_split(X, Y_new, test_size=0.33)
from sklearn import svm
clf=svm.SVC(coef0=0.0)
clf.fit(X_new_train,y_new_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [382]:
y_new_pred = clf.predict(X_new_test)
count = 0 
for j in range (y_new_test.shape[0]):
    if y_new_test[j] == y_new_pred[j]:
        count = count + 1
print count*100.0/y_new_test.shape[0]

16.8539325843


In [383]:
y_new_pred = clf.predict(X_new_train)
count = 0 
for j in range (y_new_train.shape[0]):
    if y_new_train[j] == y_new_pred[j]:
        count = count + 1
print count*100.0/y_new_train.shape[0]

19.0036900369


In [384]:
print X_new_test.shape[0]

267


In [389]:
from sklearn.ensemble import RandomForestClassifier
ran = RandomForestClassifier(max_depth=20, random_state=0)
ran.fit(X_new_train,y_new_train)
print X_new_train[17]

[0.45217141 0.25131211 0.85579393]


In [386]:
y_new_pred = ran.predict(X_new_train)
count = 0 
for j in range (y_new_train.shape[0]):
    if y_new_train[j] == y_new_pred[j]:
        count = count + 1
print count*100.0/y_new_train.shape[0]

98.5239852399


In [387]:
y_new_pred = ran.predict(X_new_test)
count = 0 
for j in range (y_new_test.shape[0]):
    if y_new_test[j] == y_new_pred[j]:
        count = count + 1
print count*100.0/y_new_test.shape[0]

48.3146067416


In [369]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=1)
neigh.fit(X_new_train, y_new_train) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [370]:
y_new_pred = neigh.predict(X_new_train)
count = 0 
for j in range (y_new_train.shape[0]):
    if y_new_train[j] == y_new_pred[j]:
        count = count + 1
print count*100.0/y_new_train.shape[0]

100.0


In [371]:
y_new_pred = neigh.predict(X_new_test)
count = 0 
for j in range (y_new_test.shape[0]):
    if y_new_test[j] == y_new_pred[j]:
        count = count + 1
print count*100.0/y_new_test.shape[0]

49.063670412
